default:
  image: openjdk:11

stages:
  - build
  - publish_image

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build

build:
  stage: build
  variables:
    DOCKER_HOST: "tcp://dind:2375"
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - ./gradlew clean build

publish_image:
  stage: publish_image
  variables:
    DOCKER_HOST: "tcp://dind:2375"
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - ./gradlew buildAppDockerImage

after_script:
  - echo "End CI"