spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/oracle}
    username: ${DATABASE_USERNAME:oracle}
    password: ${DATABASE_PASSWORD:oracle}
    driverClassName: org.postgresql.Driver

xmpp:
  domain: ${XMPP_DOMAIN:jabber.hot-chilli.net}
  userName: ${XMPP_USERNAME:oracle}
  password: ${XMPP_PASSWORD:oracle}
  host: ${XMPP_HOST:jabber.hot-chilli.net}

web3:
  host: http://localhost:8545