spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/oracle}
    username: ${DATABASE_USERNAME:oracle}
    password: ${DATABASE_PASSWORD:oracle}
    driverClassName: org.postgresql.Driver

xmpp:
  domain: ${XMPP_DOMAIN:jabber.hot-chilli.net}
  userName: ${XMPP_USERNAME:oracle}
  password: ${XMPP_PASSWORD:oracle}
  host: ${XMPP_HOST:jabber.hot-chilli.net}

wallet:
  privateKey: ${ACCOUNT_PRIVATE_KEY:e5cdf22794357fa5e03e4c92bb1a71c52817669fb6eb60663d8d341e0fdb8a03}

web3:
  host: ${WEB3_HOST:http://localhost:8545}

libsodium:
  path: /usr/lib/libsodium.so