server:
  port: 8090

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/oracle}
    username: ${DATABASE_USERNAME:oracle}
    password: ${DATABASE_PASSWORD:oracle}
    driverClassName: org.postgresql.Driver

xmpp:
  domain: ${XMPP_DOMAIN:xmpp.kyc3.com}
  host: ${XMPP_HOST:xmpp.kyc3.com}
  user:
    password: ${XMPP_PASSWORD:oracle}
  admin:
    userName: ${XMPP_ADMIN_USERNAME:igor@xmpp.kyc3.com}
    password: ${XMPP_ADMIN_PASSWORD:A4Uj7EeQmqRKxTnXBu26yPrg+vJz/NLf3ZbGFad5}

wallet:
  privateKey: ${ACCOUNT_PRIVATE_KEY:cb1069723edbac7cf03e653c34bd1e273bb17e052645904aeefc8fc30a562191}

web3:
  host: ${WEB3_HOST:https://public-node.testnet.rsk.co}

libsodium:
  path: /usr/lib/libsodium.so

contracts:
  cashier: ${CASHIER_CONTRACT_ADDRESS:0x7b7Ec4C333fC5E3D0B4001fC818491A7AE59a407}
  trust-token: ${TRUST_TOKEN_ADDRESS:0x053965Ca43f024d701AA4bF5c39db8aAcfCCF1A0}
  erc20: ${ERC20_ADDRESS:0x4d26774771a9D7CA38Ae419b695deC042B25e98d}